version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  miwifi-exporter:
    build: ./miwifi-exporter
    image: miwifi-exporter:latest
    container_name: miwifi-exporter
    restart: always
    ports:
      - "9001:9001"
    environment:
      - ROUTER_IP=XXX
      - ROUTER_PASSWORD=XXX
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

volumes:
  grafana_data:
  prometheus_data:
