{
 "title": "Xiaomi-Router",
 "description": "https://github.com/NERVEbing/miwifi_exporter",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Dispositivos online",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miwifi_count_online" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "max(miwifi_uptime)" }
   ]
  },
  {
   "title": "Rede Wi-Fi",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miwifi_wifi_detail", "legendFormat": "{{ssid}} - {{band_list}} " }
   ]
  },
  {
   "title": "Max Download",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "miwifi_wan_download_speed * 1.073741824 * 8"
    }
   ]
  },
  {
   "title": "Max Upload",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "miwifi_wan_upload_speed * 1.073741824 * 8"
    }
   ]
  },
  {
   "title": "Baixado",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "miwifi_wan_download_traffic * 1.073741824"
    }
   ]
  },
  {
   "title": "Enviado",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "miwifi_wan_upload_traffic * 1.073741824"
    }
   ]
  },
  {
   "title": "Freq. CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Mhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miwifi_cpu_mhz" }
   ]
  },
  {
   "title": "Núcleos CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miwifi_cpu_cores" }
   ]
  },
  {
   "title": "Dispositivos conectados à rede",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "miwifi_count_all",
     "legendFormat": "Número total de dispositivos históricos"
    },
    {
     "expr": "miwifi_count_online",
     "legendFormat": "Número de dispositivos online atualmente"
    }
   ]
  },
  {
   "title": "Taxa de transferência WAN",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "miwifi_wan_download_speed * 1.073741824 * 8",
     "legendFormat": "Velocidade de download"
    },
    {
     "expr": "miwifi_wan_upload_speed * 1.073741824 * 8",
     "legendFormat": "Velocidade de upload"
    }
   ]
  },
  {
   "title": "Total de download dos dispositivos conectados",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miwifi_device_download_traffic", "legendFormat": "{{ device_name }}" }
   ]
  },
  {
   "title": "Total de upload dos dispositivos conectados",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miwifi_device_upload_traffic", "legendFormat": "{{ device_name }}" }
   ]
  },
  {
   "title": "Uso da memória",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miwifi_memory_usage" }
   ]
  },
  {
   "title": "Taxa de download",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "miwifi_device_download_speed * 1.073741824 * 8",
     "legendFormat": "{{ device_name }}"
    }
   ]
  },
  {
   "title": "Taxa de download",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "miwifi_device_download_speed * 1.073741824 * 8",
     "legendFormat": "{{ device_name }}"
    }
   ]
  }
 ]
}