version: "3"

services:
  miwifi-exporter:
    build: .
    image: miwifi-exporter:latest
    container_name: miwifi-exporter
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - "9001:9001"
    environment:
      - ROUTER_IP=xxx
      - ROUTER_PASSWORD=xxx
      - ROUTER_HOST=xxx
